# Generated by Django 3.1.3 on 2020-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('monitor_price', models.CharField(max_length=20)),
                ('recent_price', models.CharField(max_length=20)),
                ('monitor_type', models.CharField(max_length=5)),
            ],
        ),
    ]
